### ISSUE TITLE
[Docs] URL link to RF Remote is not available

### ISSUE THREAD

**Issue by zhou9110** [tuya/tuya-panel-demo#208]
Hi, I am trying to integrate with an IR + RF remote control, and I saw the documentation contains a link to this repository, (link: https://github.com/tuya/tuya-panel-demo/tree/master/examples/rfRemote), however the folder doesn't exist in this repo.

Just wondering where can I find that code?

Link to the Docs: https://developer.tuya.com/en/docs/iot/rf-basic-template?id=Kb9ozf6hljcpu#title-1-Directories

您好，我正在尝试与红外+射频遥控器集成，我看到文档中包含一个链接到这个资源库，（链接：https://github.com/tuya/tuya-panel-demo/tree/master/examples/rfRemote），然而这个文件夹在这个资源库中并不存在。

我想知道在哪里可以看到这部分相关的代码？

文档的链接：https://developer.tuya.com/en/docs/iot/rf-basic-template?id=Kb9ozf6hljcpu#title-1-Directories

**Comment by ShinyLeee** [comment]
Sorry, this demo is temporarily unavailable. We will withdraw this document and apologize for the inconvenience.
