### ISSUE TITLE
Failed at the tuyaPanelExample@1.0.0 bundle-ios script

### ISSUE THREAD

**Issue by cswww** [tuya/tuya-panel-demo#6]
运行打包ios的时候出现

1.react-native bundle --platform ios
2.Failed at the tuyaPanelExample@1.0.0 bundle-ios script

**Comment by ShinyLeee** [comment]
建议使用我们提供的 tuya-panel-kit-cli 工具进行打包，具体文档可参考[工程打包](https://developer.tuya.com/cn/docs/iot/panel-development/panel-sdk-development/5-min/quick-start?id=K9mfe9upokqq6#title-10-%E5%B7%A5%E7%A8%8B%E6%89%93%E5%8C%85)
